### ISSUE TITLE
Add browser support

### ISSUE THREAD

**Issue by nonplus** [erictrinh/safe-access#3]
I'd like to use safe-access in my browser app.  Right now it's set up as a Node module.

In order to support it in a browser, the following should be added:
- Add wrapper to make it Node, AMD and browser compatible
- Add a bower configuration s.t. it can be published/accessed via [bower](http://bower.io/docs/creating-packages)
- Documentation should be update with browser instructions

I'd be happy to make these changes and issue a PR.

**Comment by erictrinh** [comment]
Thanks for the PR again! I just registered the package on bower and added installation instructions to the readme.

**Comment by nonplus** [comment]
Cool.  You should also [bump the version for bower](http://bower.io/docs/api/#version) and [for npm](https://www.npmjs.org/doc/cli/npm-version.html) to 0.2.0 or 0.1.1 and then [release it through GitHub](https://help.github.com/articles/creating-releases/).

**Comment by erictrinh** [comment]
Will do!

**Comment by erictrinh** [comment]
Done! Thanks for your help with this @nonplus.
